version: "2"
services:
 node:
   image: node:8.9
   ports:
    - 3011:3011
   working_dir: /usr/local/src/app
   volumes:
    - .:/usr/local/src/app
   command: bash -c "npm install typescript -g && npm install && npm start"
   environment:
     PORT: 3011
