version: "2"
services:
# node:
#   image: node:8.9
#   ports:
#    - 3011:3011
#   working_dir: /usr/local/src/app
#   volumes:
#    - .:/usr/local/src/app
#   command: bash -c "npm install typescript -g && npm install typeorm -g && npm install && npm start"
#   environment:
#     PORT: 3011

 database:
    image: postgres:9.6
    ports:
     - 5411:5432
    volumes:
     - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Eh7gLagHHHzK2h7j
      POSTGRES_USER: starter_user
      POSTGRES_DB: starter_db

volumes:
 data: {}
